name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update; sudo apt-get install lua5.2 make zip

    - name: Run check
      run: make package clean

    - name: Save the build
      uses: actions/upload-artifact@v4.4.3
      with:
        path: pkg/
        if-no-files-found: error
        overwrite: true
